from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

# ----------------------------------------------------
# 1. Chat Endpoint Schemas (/api/chat)
# ----------------------------------------------------

class ChatRequest(BaseModel):
    session_id: str = Field(..., description="Unique ID for the patient's current kiosk session")
    user_input: str = Field(..., description="The translated English text of what the patient said/typed")
    treatment_pathway: str = Field(
        ..., 
        description="Either 'allopathy' or 'ayurveda' to route to the correct LLM prompt"
    )

class ChatResponse(BaseModel):
    session_id: str
    ai_reply_text: str = Field(..., description="The next question generated by the LLM in English")
    is_emergency: bool = Field(default=False, description="True if red flags like chest pain are detected")
    interview_complete: bool = Field(default=False, description="True if the LLM has gathered all history")

# ----------------------------------------------------
# 2. Finalize Endpoint Schemas (/api/finalize-history)
# ----------------------------------------------------

class FinalizeRequest(BaseModel):
    session_id: str
    abha_id: Optional[str] = Field(None, description="Patient's ABHA ID if provided")

class FinalizeResponse(BaseModel):
    status: str
    structured_history: Dict[str, Any] = Field(
        ..., 
        description="The final JSON output mapping to SOCRATES or Dashavidha Pariksha"
    )